### ISSUE TITLE
#define PERL_NO_GET_CONTEXT

### ISSUE THREAD

**Issue by vonydev** [powerman/perl-Crypt-MatrixSSL3#24]
This is a bit more complicated and it has to do with Perl's ithreads implementation.

http://www.perlmonks.org/?node_id=1078174
http://perldoc.perl.org/perlguts.html#Background-and-PERL_IMPLICIT_CONTEXT

On Perls compiled without ithreads support this compiles fine, but compilation fails when ithreads are enabled.

I think the best course is to leave this one out.

**Comment by powerman** [comment]
As far as I see in docs this issue related only to STATIC functions, which we doesn't use. Here this is stated explicitly: http://blogs.perl.org/users/nick_wellnhofer/2015/03/writing-xs-like-a-pro---perl-no-get-context-and-static-functions.html
Did you tried to compile it on ithreads perl?

**Comment by vonydev** [comment]
Yes, it fails because each function expects as first parameter a my_perl variable that needs to be set to the Perl context in which it needs to run.

We can leave the define but we'll have to add dTHX; for each function which does the same thing as not having the define in the first place.

Or we can use pTHX/aTHX but that requires more rewrite.
