### ISSUE TITLE
patch executable detection does not work everywhere

### ISSUE THREAD

**Issue by eserte** [powerman/perl-Crypt-MatrixSSL3#26]
The Makefile.PL tries to detect the existence of a patch program by executing it with invalid files and probably hoping that the exit code is not 1. But this is not the case everywhere. On debian systems:
```
$ patch bla.c.orig bla.c; echo $?
patch: **** Can't open patch file bla.c : No such file or directory
2
```
On freebsd 10.1:
```
$ patch bla.c.orig bla.c; echo $?
Hmm...  I can't seem to find a patch in there anywhere.
2
```
But on freebsd 9.2:
```
$ patch bla.c.orig bla.c; echo $?
patch: **** patch file bla.c not found: No such file or directory
1
```
Maybe it's better to check `$ENV{PATH}` for the existence of a "patch" file?

**Comment by vonydev** [comment]
Hmm. It worked everywhere I tested it.
Either test $ENV{PATH} or we can add a dummy file to test patch - whatever you prefer.

**Comment by powerman** [comment]
I'm usually do such checks using $ENV{PATH}, but that's because my modules which needs this anyway works only on *NIX and don't need to support Windows. If we'll try to check $ENV{PATH} on Windows then we probably should look both for `patch` and `patch.exe`.

**Comment by powerman** [comment]
Best solution will be to use some portable CPAN module to find out is required executable available on current platform… if such a module exists, of course - @eserte may know, he knows what's on CPAN much better than most of people. :smile:

**Comment by eserte** [comment]
File::Which exists.

For my own stuff, if I don't want to pull another CPAN dependency, I use a variation of the function below:
```
sub is_in_path {
    my($prog) = @_;
    require Config;
    %Config::Config = %Config::Config if 0; # cease -w
    my $sep = $Config::Config{'path_sep'} || ':';
    foreach (split(/$sep/o, $ENV{PATH})) {
	if ($^O eq 'MSWin32') {
	    # maybe use $ENV{PATHEXT} like maybe_command in ExtUtils/MM_Win32.pm?
	    return "$_\\$prog"     if (-f "$_\\$prog" && -x "$_\\$prog");
	    return "$_\\$prog.bat" if (-f "$_\\$prog.bat" && -x "$_\\$prog.bat");
	    return "$_\\$prog.com" if (-f "$_\\$prog.com" && -x "$_\\$prog.com");
	    return "$_\\$prog.exe" if (-f "$_\\$prog.exe" && -x "$_\\$prog.exe");
	    return "$_\\$prog.cmd" if (-f "$_\\$prog.cmd" && -x "$_\\$prog.cmd");
	} else {
	    return "$_/$prog" if (-x "$_/$prog" && !-d "$_/$prog");
	}
    }
    undef;
}
```
The MSWin32 stuff can probably be simplified by using `MM->maybe_command`. See `perldoc ExtUtils::MM_Win32` and `perldoc ExtUtils::MM_Unix`.

**Comment by powerman** [comment]
Thanks @eserte!
