### ISSUE TITLE
Change API: rename $ssl->get_readbuf to $ssl->fill_readbuf or embed it in $ssl->received_data

### ISSUE THREAD

**Issue by powerman** [powerman/perl-Crypt-MatrixSSL3#7]
Using same names as MatrixSSL is good only if Perl and C API does the same thing. In this case "same name" make it really hard to understand what it does because it does different thing.

**Comment by powerman** [comment]
Moreover… Looks like matrixSslGetReadbuf() should never return error. So we can safely croak() if matrixSslGetReadbuf() will return error, and combine $ssl->get_readbuf() and $ssl->received_data() in single call:
```perl
# Current API:
my $n = $ssl->get_readbuf($in);
die 'PS_ARG_FAIL' if $n < 0; # this is only documented error
my $rc = $ssl->received_data($n, my $buf);

# Proposed API:
my $rc = $ssl->received_data($in, my $buf);
```
And remove $ssl->get_readbuf() at all.

**Comment by powerman** [comment]
One side effect will be returning PS_SUCCESS (0) from $ssl->received_data() in case matrixSslGetReadbuf() will returns 0:
- current code in sample_functions.pl anyway works this way
- it doesn't clear in which case matrixSslGetReadbuf() may return 0 - I can imagine only reason if out of memory situation, which isn't really worth caring about
- actually only real side effect is a bit changed semantics of PS_SUCCESS return code from $ssl->received_data() - in addition to described in API doc it'll also include that "matrixSslGetReadbuf() returns 0" unclear case

**Comment by vonydev** [comment]
matrixSslGetReadbuf() returns <0 (PS_ARG_FAIL) in one case: $ssl or $in are NULL which will never happen and it's safe to ignore.

matrixSslGetReadbuf() returns 0 is not an unclear case and the logic in sample_functions.pl is a bit wrong. Here is why:

```
int32 matrixSslGetReadbuf(ssl_t *ssl, unsigned char **buf) {
    ...
    *buf = ssl->inbuf + ssl->inlen;
    return ssl->insize - ssl->inlen;
}
```

matrixSslGetReadbuf() gets as second parameter a pointer to a pointer that gets set to the internal ssl_t structure input buffer advanced with how much data is currently present in the input buffer.

matrixSslGetReadbuf() returns the number of bytes that can be added safely into to internal ssl_t input buffer. If this value is 0 then this means that the internal ssl_t input buffer is full and needs processing.

ssl_io in sample_functions.pl looks like this:

```
sub ssl_io {
    my ($ssl, $in, $out, $appIn, $appOut, $handshakeIsComplete) = @_;
    my $err = q{};
RECV:
    while (my $n = $ssl->get_readbuf($in)) {
        if ($n < 0)                                 { $err=error($n); last }
        my $rc = $ssl->received_data($n, my $buf);
RC: 
```

The while gets executed as long as $n != 0, but $n == 0 is the "worst" case (ssl_t internal input buffer full and needs processing right now) and not the "best" (no more data to process). So this should be written as:

```
sub ssl_io {
    my ($ssl, $in, $out, $appIn, $appOut, $handshakeIsComplete) = @_;
    my $err = q{}; my ($n, $rc);
RECV:
    while (length($in)) {
        $n = $ssl->get_readbuf($in);
        $rc = $ssl->received_data($n, my $buf);
RC: 
```

Regarding the unification of the two calls - I don't see a reason against it. Nothing else needs to change.

**Comment by powerman** [comment]
Thanks for the explanation!

> `while (length($in)) {`

I'm not sure this is correct. `$in` may be empty because all data from it may be moved to MatrixSSL's internal buffer, but that doesn't guarantee that internal buffer is empty too (or not empty but doesn't contain at least one full packet to process). To make it correct we probably also should replace some (or all) `next` with `redo` inside that loop… or just use `while (1) {` instead.

> Regarding the unification of the two calls - I don't see a reason against it.

Cool. Then I'll fix this issue with examples and change API by removing get_readbuf() and calling it internally within received_data().

**Comment by powerman** [comment]
> $n == 0 is the "worst" case (ssl_t internal input buffer full and needs processing right now)

Actually this should never happens. To make it happens we should receive enough data to fill that internal buffer, but that data shouldn't contain one full packet. I suppose if this happens then received_data() **must** return error (or grow that internal buffer and avoid returning 0 from get_readbuf()).

**Comment by powerman** [comment]
After double-checking current example and MatrixSSL API docs I believe it's correct.

But condition in `while (my $n = $ssl->get_readbuf($in)) {` is implicit and actually means: `while (length $in) {`, because empty $in is the only case when get_readbuf() will returns 0 (in that example script). Moreover, get_readbuf() will returns 0 in that case not because matrixSslGetReadbuf() will returns 0, but because our XS wrapper will returns 0.

**Comment by vonydev** [comment]
> Thanks for the explanation!
> 
>     while (length($in)) {
> 
> I'm not sure this is correct. $in may be empty because all data from it may be moved to MatrixSSL's internal buffer, but that doesn't guarantee that internal buffer is empty too (or not empty but doesn't contain at least one full packet to process). To make it correct we probably also should replace some (or all) next with redo inside that loop… or just use while (1) { instead.

`while (length($in))` - this is correct. matrixSSL in matrixSslReceivedData() tries to process all complete packets present in the internal buffer. If an incomplete packet is present then it returns MATRIXSSL_REQUEST_RECV signaling that more data is needed which is handled by this line in sample_function.pl:

```
    elsif ($rc==MATRIXSSL_REQUEST_RECV)         { next          } 
```


> After double-checking current example and MatrixSSL API docs I believe it's correct.
> 
> But condition in while (my $n = $ssl->get_readbuf($in)) { is implicit and actually means: while (length $in) {, because empty $in is the only case when get_readbuf() will returns 0 (in that example script). Moreover, get_readbuf() will returns 0 in that case not because matrixSslGetReadbuf() will returns 0, but because our XS wrapper will returns 0.
> 

This is get_readbuf in XS:

```
int sess_get_readbuf(ssl, inBuf);
    Crypt_MatrixSSL3_Sess *ssl;
    SV *inBuf;
    STRLEN bufsz = 0;
    unsigned char *buf = NULL;
    unsigned char *readbuf = NULL;

    CODE:
    RETVAL = matrixSslGetReadbuf((ssl_t *)ssl, &readbuf);

    if (RETVAL > 0) {
        buf = (unsigned char *) SvPV(inBuf, bufsz);
        if((unsigned int) RETVAL > bufsz)
            RETVAL = bufsz;
        memcpy(readbuf, buf, RETVAL);
        /* remove from the input whatever got processed */
        sv_setpvn_mg(inBuf, (const char *) buf+RETVAL,  bufsz-RETVAL);
    }

    OUTPUT:
    RETVAL
```
This function returns 0 when:

- matrixSslGetReadbuf() - returns 0 - no room left into ssl_t internal buffer
- inBuf empty

`while (length($in))` also takes care of the second case because the while block is executed only when $in contains something.

**Comment by powerman** [comment]
> matrixSslGetReadbuf() - returns 0 - no room left into ssl_t internal buffer

How this may happens?
If we call matrixSslGetReadbuf() twice without calling matrixSslReceivedData() it will return same results.
If we call matrixSslReceivedData(n) after matrixSslGetReadbuf() then n bytes in internal buffer will be (initially) marked as used and if matrixSslReceivedData() don't process (part of) these n bytes itself then next call to matrixSslGetReadbuf() will return buffer which size is less by n. BUT. To have matrixSslGetReadbuf() return 0 ... matrixSslGetReadbuf() should see full internal buffer when it's called, don't process even single byte from it (i.e. buffer is full but doesn't contain even one correct ssl packet), and don't return error. I believe this shouldn't happens, because if it will happens then 0 returned from matrixSslGetReadbuf() doesn't helps - we're stuck anyway and can't make any progress on this connection.
